Enhancements to Testing Infrastructure and Resolution of Merge Conflicts
ygivenx/llmtag pull request #19
Opened 2023-10-12 22:01 UTC by shaunporwal

- Unit Tests and Dependencies: Fixed unit tests and added necessary dependencies.
- Merge Conflict: Resolved a conflict with the main branch.
- File Additions: Added binary files.
- .gitignore Updates: Added new entries to exclude certain files.
- Dependency Updates: Introduced new libraries and packages in the project.
- Data Files: Updated and added data files related to benchmarking and testing.
- Test Updates: Modified test methods and introduced new ones for better coverage.

2023-10-12 22:06 UTC, ygivenx commented on tests/test_simple.py
> +    counter = 0
In conftest, we are already sampling 10 rows, the counter here is not required

2023-10-12 22:07 UTC, ygivenx commented on tests/test_simple.py
> +# def test_llm_simple_prompt(note):
please uncomment this.

2023-10-12 22:08 UTC, ygivenx commented on tests/test_simple.py
> +from .load_test_data import load_simulation_df1, load_labeled_df1, load_gpt_sim, load_gpt_sim_small
what is your reasoning behind have three load functions instead of one which takes a filename input?

2023-10-12 22:09 UTC, ygivenx commented on tests/load_test_data.py
> +def load_gpt_sim():
this can be condensed into one function

2023-10-12 22:10 UTC, ygivenx requested changes
Please take a look at the comments - let me now what you think!

2023-10-19 23:05 UTC, shaunporwal commented
Added mocking for unit tests

2023-10-19 23:14 UTC, closed without merging